#
name: Verificação de segurança com TFSEC
run-name: ${{ github.actor }} Iniciou a Verificação de segurança com TFSEC
on:
  push:
    branches: [ "main" ]
    paths:
      - '**.tf'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.tf'

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif