name: Geração da documentação do módulo
run-name: ${{ github.actor }} Iniciou a geração da documentação do módulo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tfsec:
    name: Rodando o TFDOCS
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
  
      - name: terraform-docs-gh-actions
      # You may pin to the exact commit or the version.
      # uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786
      uses: terraform-docs/gh-actions@v1.2.0