name: Geração da documentação do módulo
run-name: ${{ github.actor }} Iniciou a geração da documentação do módulo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tfdocs:
    name: Rodando o TFDOCS
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: main
          #token: ${{ secrets.WORKFLOW_TOKEN }}
          token: ${{ github.token }}

      - name: terraform-docs-gh-actions
      # You may pin to the exact commit or the version.
      # uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-push-user-name: crazybyte-rj